'use strict';

const WEAPONS = {
  dual_blades: {
    id: 'dual_blades',
    name: '절단쌍검',
    archetype: 'fast_onhit',
    baseDps: 34,
    attackSpeed: 1.35,
    critBias: 0.10,
    areaBias: -0.05,
    range: 0.35,
    survival: 0.88,
    affinities: {
      attackSpeed: 1.20,
      extraHit: 1.20,
      crit: 0.90,
      dot: 1.10,
      projectile: 0.70,
      area: 0.75,
      control: 0.85,
      burst: 0.85,
    },
  },
  greatsword: {
    id: 'greatsword',
    name: '장송대검',
    archetype: 'slow_burst',
    baseDps: 38,
    attackSpeed: 0.78,
    critBias: 0.18,
    areaBias: 0.10,
    range: 0.48,
    survival: 0.92,
    affinities: {
      attackSpeed: 0.72,
      extraHit: 0.75,
      crit: 1.28,
      dot: 0.75,
      projectile: 0.80,
      area: 1.12,
      control: 0.90,
      burst: 1.24,
    },
  },
};

const MEMORIES = {
  execution_flash: {
    id: 'execution_flash',
    name: '처형자의 섬광',
    role: 'burst',
    active: '주기적 강타',
    baseDps: 22,
    burst: 1.00,
    dot: 0.00,
    projectile: 0.25,
    area: 0.25,
    control: 0.00,
    onhit: 0.20,
    bossBias: 1.15,
    crowdBias: 0.78,
    presence: 0.74,
    echo: { critChance: 0.080, critDamage: 0.160 },
    echoTags: ['crit', 'burst'],
  },
  hungry_blades: {
    id: 'hungry_blades',
    name: '굶주린 칼무리',
    role: 'dot',
    active: '근접 지속 피해 오라',
    baseDps: 18.5,
    burst: 0.08,
    dot: 0.95,
    projectile: 0.00,
    area: 0.58,
    control: 0.05,
    onhit: 0.45,
    bossBias: 0.90,
    crowdBias: 1.18,
    presence: 0.95,
    echo: { attackSpeed: 0.090, dotPower: 0.160 },
    echoTags: ['attackSpeed', 'dot'],
  },
  tracker_oath: {
    id: 'tracker_oath',
    name: '추적자의 맹세',
    role: 'projectile',
    active: '자동 유도 투사체',
    baseDps: 18,
    burst: 0.35,
    dot: 0.00,
    projectile: 1.00,
    area: 0.12,
    control: 0.05,
    onhit: 0.22,
    bossBias: 1.04,
    crowdBias: 0.92,
    presence: 0.86,
    echo: { projectileCount: 0.080, homing: 0.140 },
    echoTags: ['projectile'],
  },
  shattering_ripple: {
    id: 'shattering_ripple',
    name: '파쇄의 파문',
    role: 'area',
    active: '원형 충격파와 넉백',
    baseDps: 17,
    burst: 0.20,
    dot: 0.10,
    projectile: 0.00,
    area: 1.00,
    control: 0.35,
    onhit: 0.00,
    bossBias: 0.82,
    crowdBias: 1.32,
    presence: 0.82,
    echo: { area: 0.120, knockback: 0.160, survival: 0.030 },
    echoTags: ['area', 'survival'],
  },
  blood_reflection: {
    id: 'blood_reflection',
    name: '피의 반사',
    role: 'onhit',
    active: '공격 시 추가타',
    baseDps: 16,
    burst: 0.15,
    dot: 0.20,
    projectile: 0.05,
    area: 0.08,
    control: 0.00,
    onhit: 1.00,
    bossBias: 1.02,
    crowdBias: 0.98,
    presence: 0.88,
    echo: { extraHitChance: 0.090, onHitDamage: 0.170 },
    echoTags: ['extraHit', 'onhit'],
  },
  stopped_second: {
    id: 'stopped_second',
    name: '멈춘 초침',
    role: 'control',
    active: '둔화/시간 균열',
    baseDps: 12,
    burst: 0.05,
    dot: 0.10,
    projectile: 0.10,
    area: 0.42,
    control: 1.00,
    onhit: 0.05,
    bossBias: 0.72,
    crowdBias: 0.86,
    presence: 0.78,
    echo: { cooldownReduction: 0.085, slowDuration: 0.160, survival: 0.035 },
    echoTags: ['control', 'cooldown'],
  },
};

const MEMORY_FORGET_BIAS = {
  execution_flash: 0.74,
  hungry_blades: 0.82,
  tracker_oath: 0.98,
  shattering_ripple: 1.06,
  blood_reflection: 1.08,
  stopped_second: 1.10,
};

const SYNERGIES = [
  { a: 'execution_flash', b: 'tracker_oath', name: '유도 섬광', bonus: 0.13, tags: ['burst', 'projectile'] },
  { a: 'hungry_blades', b: 'blood_reflection', name: '굶주린 반사', bonus: 0.18, tags: ['dot', 'onhit'] },
  { a: 'shattering_ripple', b: 'stopped_second', name: '정지 충돌', bonus: 0.16, tags: ['area', 'control'] },
  { a: 'execution_flash', b: 'blood_reflection', name: '피묻은 섬광', bonus: 0.10, tags: ['crit', 'onhit'] },
  { a: 'hungry_blades', b: 'shattering_ripple', name: '칼날 파문', bonus: 0.11, tags: ['dot', 'area'] },
  { a: 'tracker_oath', b: 'stopped_second', name: '멈춘 표적', bonus: 0.12, tags: ['projectile', 'control'] },
  { a: 'execution_flash', b: 'shattering_ripple', name: '파쇄 처형', bonus: 0.09, tags: ['burst', 'area'] },
  { a: 'blood_reflection', b: 'stopped_second', name: '느린 출혈', bonus: 0.08, tags: ['onhit', 'control'] },
];

const ENCOUNTERS = {
  room: {
    name: '일반 전투',
    durationSec: 130,
    crowd: 0.62,
    single: 0.38,
    boss: 0.00,
    danger: 0.45,
    preferred: { area: 0.85, dot: 0.55, projectile: 0.35, burst: 0.30, control: 0.45, onhit: 0.45 },
  },
  elite: {
    name: '엘리트 전투',
    durationSec: 50,
    crowd: 0.48,
    single: 0.52,
    boss: 0.20,
    danger: 0.62,
    preferred: { area: 0.50, dot: 0.45, projectile: 0.48, burst: 0.62, control: 0.55, onhit: 0.48 },
  },
  boss: {
    name: '기억을 씹는 자',
    durationSec: 60,
    crowd: 0.36,
    single: 0.64,
    boss: 1.00,
    danger: 0.78,
    phases: [
      { name: '잡몹 소환', weight: 0.30, preferred: { area: 0.85, dot: 0.68, projectile: 0.25, burst: 0.32, control: 0.45, onhit: 0.42 } },
      { name: '도주/원거리', weight: 0.28, preferred: { area: 0.25, dot: 0.30, projectile: 0.85, burst: 0.58, control: 0.40, onhit: 0.35 } },
      { name: '짧은 그로기', weight: 0.27, preferred: { area: 0.25, dot: 0.25, projectile: 0.45, burst: 0.92, control: 0.20, onhit: 0.55 } },
      { name: '위험 장판', weight: 0.15, preferred: { area: 0.35, dot: 0.20, projectile: 0.25, burst: 0.25, control: 0.82, onhit: 0.30 } },
    ],
  },
};

const DEFAULT_TARGETS = {
  regretRateMin: 0.60,
  irritationRateMax: 0.03,
  dullRateMax: 0.25,
  predictionMatchMin: 0.75,
  predictionMatchMax: 0.90,
  immediateQuitMax: 0.15,
  restartRateMin: 0.60,
  firstForgetUseMinSec: 210,
  firstForgetUseMaxSec: 270,
  maxBuildClassShare: 0.80,
  maxSingleMemoryDeleteShare: 0.35,
  maxMemoryDeleteSpread: 0.35,
  echoPowerSweetSpotMin: 0.50,
  echoPowerSweetSpotMax: 0.70,
  postForgetDropMin: 0.30,
  postForgetDropMax: 0.40,
  recoveryMin: 0.90,
  recoveryMax: 1.10,
  earlyFunScoreMin: 0.72,
  earlyLevelUpsMin: 2,
  earlyKillTempoMin: 0.68,
  firstCycleCompletionRateMin: 0.70,
  twoMemorySurvivalRateMin: 0.65,
  twoMemorySurvivalRateMax: 0.88,
  echoPivotScoreMin: 0.62,
  refillReachedRateMin: 0.70,
};

const SIM_DEFAULTS = {
  runs: 1000,
  stages: 3,
  seed: '20260601',
  echoPower: 0.50,
  uiClarity: 0.78,
  replacementOffer: true,
  enableHumanEmotionProxy: true,
  earlyEnemyPressure: 0.86,
  runGrowthChoices: true,
};

module.exports = {
  WEAPONS,
  MEMORIES,
  MEMORY_FORGET_BIAS,
  SYNERGIES,
  ENCOUNTERS,
  DEFAULT_TARGETS,
  SIM_DEFAULTS,
};
